config/routes.rb
Bloom::Application.routes.draw do
  
  get "recurly/billing"
  get "recurly/account"
  post "recurly/push"
  get "recurly/test"
  get "recurly/test_new_subscription"
  post "recurly/push_new_subscription"
  get "recurly/test_declined_payment"
  post "recurly/push_declined_payment"
  get "recurly/test_successful_payment"
  post "recurly/push_successful_payment"

  get "session/new"
  resources :users
  resources :checkouts
  resources :session
  resources :ship_addresses
  resources :user_orders
  resources :subscriptions
  resources :products

   get 'export' => 'subscriptions#export'
   post 'export' => 'subscriptions#export_action'

   get 'export_action' =>'subscriptions#export_action'
   get 'update' => 'subscriptions#update_ship_dates'
   get 'all/dashboard' =>  'subscriptions#index'
   get 'active/dashboard' =>  'subscriptions#index_active'
   get 'update_ship'=> 'subscriptions#edit_ship_address'
   post 'update_ship'=> 'subscriptions#update_ship_address'


  get "site/index" 
  get "site/privacy"
  get "site/terms"

  root 'site#index'
  
  get 'dashboard' => 'subscriptions#index_active'

  get 'signup' =>  "users#new"
  delete 'logout' => "session#destroy"
  get "logout" => "session#destroy"

  post 'users/new' => "users#create"
  post 'session/new' => 'session#create'

  get 'flowers' => 'site#subscribe'
  post 'site/subscribe' => 'site#subscribe_create'

  get 'registration' => 'recurly#billing'
  get 'registrations/new'


end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
 require "comma"
 # before_save :calculate_next_ship

  # ================
   # = Associations =
   # ================
	belongs_to :user
  belongs_to :ship_address




  # comma is a gem that allows me to export to csv
 comma do
 	  subscription_type
    subscription_status
    next_shipment
    ship_address :company
 		ship_address :first_name
    ship_address :last_name
    ship_address :address1
    ship_address :address2
    ship_address :city	
    ship_address :state
    ship_address :postalcode
    ship_address :country

  end

  #changes order status to expired when push notification come from recurly

	def expire
	  self.subscription_status="expired"
	  self.save
	end

	def active 
		self.subscription_status="active"
		self.save
	end
	
	def declined 
		self.subscription_status="declined"
		self.save
	end

	def frequency_pretty
		if self.subscription_frequency == '2week'
			self.subscription_frequency = '2 Weeks'


		elsif self.subscription_frequency == '4week'
			self.subscription_frequency = '4 Weeks'
	

		elsif self.subscription_frequency == 'holiday'
			self.subscription_frequency = 'Major Holiday'
		end
	end
	

	#calculates next ship date for 
	def calculate_next_ship 
		calculated_date=Date.new
		if self.next_shipment != nil
		if self.next_shipment < Date.today
			if subscription_frequency == "4week"
				calculated_date = self.next_shipment + 28.day
				self.next_shipment = 	calculated_date		
			end
				if subscription_frequency == "2week"
				calculated_date = self.next_shipment + 14.day
				self.next_shipment = 	calculated_date		
			end
		end
		end
	end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
 # before_filter :authorize 
  layout "dashboard"
	def index

		@subscriptions=Subscription.all
 

	end

	def index_active
		@subscriptions_active=Subscription.where(:subscription_status => "active") 
	end

# def create 
# 	 @subscription = Subscription.new(subscription_params)
#    @subscription.next_shipment = @subscription.start_date
#    @subscription.save
# 	redirect_to new_ship_address_path
# end


  def subscription_params
  	params.permit(:subscription_type, :subscription_frequency, :start_date)
  end


	def show

		@subscription = Subscription.find params[:id]
		
		account = Recurly::Account.find(@subscription.user_id)
			@billing_info = account.billing_info
		  @billing_first_name = account.first_name
		  @billing_last_name = account.last_name
		  @billing_first_name = account.first_name


		 @type = @subscription.subscription_type
		 @frequency = @subscription.subscription_frequency
		 @status = @subscription.subscription_status
		 @next_shipment = @subscription.next_shipment


		 @shipping_first_name  = @subscription.ship_address.first_name
		 @shipping_last_name = @subscription.ship_address.last_name
		 @shipping_company = @subscription.ship_address.company
		 @shipping_address1 = @subscription.ship_address.address1
		 @shipping_address2 = @subscription.ship_address.address2
		 @shipping_city = @subscription.ship_address.city
		 @shipping_state = @subscription.ship_address.state
		 @shipping_zip = @subscription.ship_address.postalcode


		
	end


	def export
		@subscriptions=Subscription.first

  end

  def export_action
  	@today = Date.today
  	@filename = "Gilded Blooms " + @today.to_s + ".csv"
		@ship_date_input = params[:ship_date]
  	if @ship_date_input == nil
	  	respond_to do |format|
	   		format.csv { render :csv => Subscription.all, :filename => 'books.csv' }
	  	end
  	else
	 		@ship_date_input = params[:ship_date]
	   	respond_to do |format|
	   		format.csv { render :csv => Subscription.where(:next_shipment => @ship_date_input, :subscription_status => 'active'),:filename => @filename }
  		end
  	end
	end


  def update_ship_dates
  	@subscriptions=Subscription.all 
  	@subscriptions.each do |sub|
  		sub.calculate_next_ship
  		sub.save
  	end		
  	redirect_to dashboard_path
	end





end

app/views/subscriptions/edit_ship_address.html.erb
<%= form_for(@ship_address) do |f| %>
  
    <div class="field">
    <%= f.label :company, 'Company' %><br>
    <%= f.text_field :company %>
  </div>

   <div class="field">
    <%= f.label :first_name, 'First Name' %><br>
    <%= f.text_field :first_name, :required => true, :value => @user.first_name %>
  </div>

   <div class="field">
    <%= f.label :last_name, 'Last Name' %><br>
    <%= f.text_field :last_name, :required => true %>
  </div>

  <div class="field">
    <%= f.label :address1, 'Address' %><br>
    <%= f.text_field :address1, :required => true %>
  </div>

 <div class="field">
    <%= f.label :address2, 'Appartment or Suite Number' %><br>
    <%= f.text_field :address2 %>
  </div>

 <div class="field">
    <%= f.label :city, 'City' %><br>
    <%= f.text_field :city, :required => true %>
  </div>

 <div class="field">
    <%= f.label :state, 'State' %><br>
    <%= f.text_field :state,  :required => true %>
  </div>


 <div class="field">
    <%= f.label :postalcode, 'Postal Code' %><br>
    <%= f.text_field :postalcode, :required => true %>
  </div>

  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.hidden_field :plan, :value => @plan %>


  <div class="actions">
    <%= submit_tag("Next Step") %>
  </div>
<% end %>

app/views/subscriptions/export.html.erb
<div style='height: 40px'></div>

<h1 style="font-size: 30px;"> Export Order for Delivery </h1>
 
<h2> Select Date or Date Range </h2>

<div id="date_selector">

 <%= form_tag :format => "csv"  do %>

  <div class="field">

    <%=  date_field_tag :ship_date, value = Date.today %>
  </div>
  <div class="actions">
    <%= submit_tag("Export Now", :class => 'button export') %>
  </div>

<% end %>

</div>

app/views/subscriptions/index.html.erb
<div class='dash_content'> 

	<div class="filter_row">
		View: <%=link_to "Active", active_dashboard_path, :id=>"filter_link"  %> <span style="color: #f5989d">All</span>
	</div>

	<table cellspacing="0"  id="subscriptions">
		<tr> 
			<th>
				Acct # 
			</th>
			<th>
				Name
			</th>
			<th>
				Email
			</th>
			<th>
				Status
			</th>
			<th>
				Next Shipment
			</th>
		</tr>



		<% @subscriptions.each do |sub| %>
			<tr> 
				<td>
					<%=link_to sub.id, subscription_path(sub.id) %>
				</td>
				<td>
					<%=	sub.user.first_name %>
		 		</td>
			
					<td>
					<%= sub.user.email %>	
				</td>
					<td>
					<%= sub.subscription_status %>
				</td>
					<td>
					<%= sub.next_shipment %>
					
				</td>
			</tr>

		<%end%>


	</table>
		
</div>

app/views/subscriptions/index_active.html.erb
<div class='dash_content'> 

	<div class="filter_row">
	View: <span style="color: #f5989d">Active</span> 	<%=link_to "All", all_dashboard_path, :id=>"filter_link" %>
	</div>

	<table cellspacing="0"  id="subscriptions">
		<tr> 
			<th>
				Acct # 
			</th>
			<th>
				Name
			</th>
			<th>
				Email
			</th>
			<th>
				Status
			</th>
			<th>
				Next Shipment
			</th>
		</tr>



		<% @subscriptions_active.each do |sub| %>
			<tr> 
				<td>
					<%=link_to sub.id, subscription_path(sub.id) %>
				</td>
				<td>
					<%=	sub.user.first_name %>
		 		</td>
			
					<td>
					<%= sub.user.email %>	
				</td>
					<td>
					<%= sub.subscription_status %>
				</td>
					<td>
					<%= sub.next_shipment %>
					
				</td>
			</tr>

		<%end%>


	</table>
		
</div>

app/views/subscriptions/show.html.erb
	

	<head>
		<meta charset="utf-8"/>
		<title></title>
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href=""/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>


		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->
	</head>




	<div id='sub_bar'>
	   <div id='username'><%= @subscription.user.first_name %>'s Account 
	   </div>
	</div>
	
	<div class='account_content'> 
			<div class='smallSubBoxWrapper billing'>
				<h3 style="	display:inline-block;">Billing Information</h3> 
					<div class="edit_link"><%= link_to 'Edit' , edit_ship_address_path %>
					</div>
				<div class="smallSubBox"> 
					<p>
						<%= @billing_info.first_name %>
						<%= @billing_info.last_name %>
					</p>
					<p>
						<%= @billing_info.address1 %>
					</p>
					<p>
						<%= @billing_info.address2 %>
					</p>
					<p>
						<%= @billing_info.city %>, <%= @billing_info.state %> <%= @billing_info.zip %>
					</p>

					<p>
						credit card: <%= @billing_info.last_four %> 
						expires: <%= @billing_info.month %>/<%= @billing_info.year %> 
					</p>

				</div>
			</div>

			<div class='smallSubBoxWrapper shipping'>
				<h3>Shipping Information</h3>
						<div class='edit_link'>
							<%= link_to 'Edit' , edit_ship_address_path(@subscription.ship_address.id) %>
						</div>
				<div class="smallSubBox ">

					<p>
						<%= @shipping_first_name %> <%= @shipping_last_name %>
					</p>
					
					<p>
						
					</p>
					
					<p>
						<%= @shipping_address1 %> 
					</p>

					<p>
						<%= @shipping_address2 %> 
					</p>

					<p>
						<%= @shipping_city %>, <%= @shipping_state %>  <%= @shipping_zip %> 
					</p>

				</div>
			</div>
		



			
			<div class='smallSubBoxWrapper billing'>
				<h3>Subscription Info</h3>
				<div class="smallSubBox"> 
					<p>
						Type: <%= @type %>
					
					</p>
					<p>
						Frequency: <%= @frequency %>
					</p>
					<p>
						Status: <%= @status %>
					</p>
					<p>
						Next Shipment: <%= @subscription.next_shipment%>
					</p>
				

				</div>
			</div>

			<div class='smallSubBoxWrapper shipping'>
				<h3>Subscription Actions</h3>
				<div class="smallSubBox ">
								<p>
						Delete
					
					</p>
					<p>
						Pause
					</p>
					<p>
						Update
					</p>
				</div>
			</div>
		
	</div>