config/routes.rb
Bloom::Application.routes.draw do
  
  get "recurly/billing"
  get "recurly/account"
  post "recurly/push"
  get "recurly/test"
  get "recurly/test_new_subscription"
  post "recurly/push_new_subscription"
  get "recurly/test_declined_payment"
  post "recurly/push_declined_payment"
  get "recurly/test_successful_payment"
  post "recurly/push_successful_payment"

  get "session/new"
  resources :users
  resources :checkouts
  resources :session
  resources :ship_addresses
  resources :user_orders
  resources :subscriptions
  resources :products

   get 'export' => 'subscriptions#export'
   post 'export' => 'subscriptions#export_action'

   get 'export_action' =>'subscriptions#export_action'
   get 'update' => 'subscriptions#update_ship_dates'
   get 'all/dashboard' =>  'subscriptions#index'
   get 'active/dashboard' =>  'subscriptions#index_active'
   get 'update_ship'=> 'subscriptions#edit_ship_address'
   post 'update_ship'=> 'subscriptions#update_ship_address'


  get "site/index" 
  get "site/privacy"
  get "site/terms"

  root 'site#index'
  
  get 'dashboard' => 'subscriptions#index_active'

  get 'signup' =>  "users#new"
  delete 'logout' => "session#destroy"
  get "logout" => "session#destroy"

  post 'users/new' => "users#create"
  post 'session/new' => 'session#create'

  get 'flowers' => 'site#subscribe'
  post 'site/subscribe' => 'site#subscribe_create'

  get 'registration' => 'recurly#billing'
  get 'registrations/new'


end

app/views/layouts/_header.html.erb
<header class="site-header">
	<div class="signup-bar">
		<div id='headerContainer'>
			<a href = '/'><%= image_tag('../images/bly.jpg', class: 'headerLogo')  %> </a>
			
			<div id='headerLinks'>
				<%	if session[:user_id] == nil %>
					<a class=" btn btn-nav content-no-logged-in" href="/signup" data-panel-nav="clear">SUBSCRIBE</a>
				<%end%>
				
				<% if session[:user_id] %>
				<%= link_to 'LOG OUT' , logout_path %>
					<%= link_to 'MY ACCOUNT' , user_orders_path(session[:user_id])%>
				<% else %>
					<%= link_to 'MY ACCOUNT', new_session_path %>
				<%end%>
				<a href="#"> BLOG </a>
				<a href="#"> GIFT </a>
				<a href="#"> ABOUT </a>
			
		</div>
		
		</div>
	</div>
</header>

<div style="height:35px">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Bloom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

		<link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>
		
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render partial: 'layouts/header'%> 

<div style="height:30px"></div>

<%= yield %>


</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
	<head>

	  <title>Bloom</title>

	  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>
	  
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>

<%= render partial: 'layouts/dashboardheader'%> 


		<%= yield %>


	</body>
</html>